tasks:
  - init: pnpm i
    command: pnpm run dev

ports:
  - port: 3000
    onOpen: open-browser

image:
  file: .gitpod/.gitpod.dockerfile

vscode:
  extensions:
    - 'svelte.svelte-vscode'
    - 'bradlc.vscode-tailwindcss'

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
